Przemek/jpydzr5 rfd 68/zmiana biblioteki datetime na pendulum
infoshareacademy/jpydzr5-reservation-for-destination pull request #45
Opened 2024-08-12 19:39 UTC by PrzemyslawMakowka84

2024-08-13 06:46 UTC, SledgehammerPL requested changes
Jeśli nigdzie więcej nie ma odwołania do czasu to spoko, ale wydawało mi się, że gdzieś widziałem datetime - ale może to było w części konsolowej

Dam Approve jak zmienisz settings.py - bo to jest krytyczny błąd

2024-08-13 06:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema/views.py
> +    for day in range(1, 8):
chyba seven :D

2024-08-13 06:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema/views.py
> +    return TemplateResponse(request, template, sever_days)
zamiast sever_days sugerowałbym context albo dictionary albo params - chodzi o to żeby w TemplateResponse było zawsze request, template, context - w każdym widoku - żeby nazwać zmienna przekazywaną w jeden - identyczny dla całego projektu sposób - żeby nie trzeba się było zastanawiać do czego te sever_days służy

2024-08-13 06:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema_reservation_system/wsgi.py
No tu masz błąd który powoduje że nie widzi cinema.

2024-08-13 06:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema/templates/cinema/repertoire.html
css powinien być w pliku osobnym a nie w html, ale to może być jako osobny task - bo to trzeba złapać o co chodzi w django - collectstatic

2024-08-13 06:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema_db.sqlite
moim zdaniem ten plik nie powinien być w githubie - bo każdy ma swój i jak coś dodam, usunę, to potem nadpisze innym

2024-08-13 19:13 UTC, PrzemyslawMakowka84 commented on cinema_reservation_system/cinema/views.py
> +    return TemplateResponse(request, template, sever_days)
A to nie jest za bardzo wtedy uogólnione? Jak byś mial bardziej skąplikowany widok nie lepiej stosować bardziej podpwiadające nazwy? Taka jest zasada jeśli chodzi o Twoja sugesrię?

2024-08-13 19:18 UTC, PrzemyslawMakowka84 commented on cinema_reservation_system/cinema/templates/cinema/repertoire.html
PRzemycę to w tym zadaniu

2024-08-14 07:31 UTC, SledgehammerPL approved these changes

2024-08-14 07:35 UTC, merged