Testy
infoshareacademy/jpydzr5-reservation-for-destination pull request #48
Opened 2024-08-15 11:03 UTC by Eleorad

2024-08-15 17:53 UTC, PrzemyslawMakowka84 commented on cinema_reservation_system/cinema/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
A co się stanie jeśli np test w tej linijce się wywali? Czy wtedy pozostałe też się wykonają czy nie? Co z pozostałymi metodami testujacymi?

2024-08-16 10:03 UTC, Eleorad commented on cinema_reservation_system/cinema/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
Co ten test robi?
-test_index_view: Sprawdza, czy widok index zwraca status 200 (OK), używa szablonu cinema/index.html i czy w kontekście znajduje się klucz menu_positions z trzema elementami.

-test_basket_view: Sprawdza, czy widok basket zwraca status 200, używa szablonu cinema/basket.html i czy w kontekście znajduje się klucz message o wartości "OK!".

-test_price_list_view: Sprawdza, czy widok price_list zwraca status 200, używa szablonu cinema/price_list.html i czy w kontekście znajduje się klucz message o wartości "OK!".

-test_repertoire_view: Sprawdza, czy widok repertoire zwraca status 200, używa szablonu cinema/repertoire.html i czy w kontekście znajduje się klucz days z 7 dniami.

2024-08-16 11:26 UTC, PrzemyslawMakowka84 commented on cinema_reservation_system/cinema/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
Ok ale według mnie powinniśmy wiedzieć czy jeśli np -test_basket_view się wywali to czy testy test_price_list_view i test_repertoire_view: ruszą? Według mnie to jest istotne.

2024-08-20 19:46 UTC, SledgehammerPL commented on cinema_reservation_system/cinema/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
Tak testy zawsze idą wszystkie i są 3 możliwe stany - ok, fail i error - fail to znaczy że wszystko zrobił jak trzeba, ale wynik jest inny od oczekiwanego, a error to znaczy że coś się po drodze wywaliło.

2024-08-20 22:26 UTC, SledgehammerPL requested changes
Wszystko ok, ale pyc trzeba wywalić...

2024-08-27 14:40 UTC, merged